name: AntiDupl CI Build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches: [ "master" ]

env:
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
  
jobs:

  build:
    
    strategy:
      matrix:
        configuration: [Debug, Release, Publish]

    runs-on: windows-latest

    env:
      Solution_Name: ./src/AntiDupl.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Read version.txt
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./src/version.txt
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.Solution_Name}}

    - name: Run and cache vcpkg dependecies
      uses: lukka/run-vcpkg@v10.7
      with:
        vcpkgGitCommitId: 223d33be7d3ec6c3d64381ca37f501b8c87dda6a
        vcpkgJsonGlob: src/vcpkg.json
        runVcpkgInstall: false
        appendedCacheKey: '${{matrix.configuration}}'

    - name: Integrate vcpkg
      working-directory: ${{env.VCPKG_ROOT}}
      run: |
        ${{ github.workspace }}/vcpkg/vcpkg.exe integrate install

    - if: matrix.configuration == 'Release' || matrix.configuration == 'Debug'
      name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=$env:Configuration $env:Solution_Name
      env: 
        Configuration: ${{ matrix.configuration }}

    - if: matrix.configuration == 'Publish'
      name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m $env:Solution_Name /p:Configuration=$env:Configuration -restore -t:Publish -p:PublishProfile="AntiDuplPublishSingleFile"
      env: 
        Configuration: ${{ matrix.configuration }}
        
    - if: matrix.configuration == 'Release'
      name: Make release binary and source files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd cmd
        .\MakeBin.cmd
      
    - if: matrix.configuration == 'Publish'
      name: Make release binary and source files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd cmd
        .\MakePublish.cmd
      
    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v3
      env:
          VT_API_KEY: ${{ secrets.VT_API_KEY }}
      if: matrix.configuration == 'Release' && env.VT_API_KEY != null
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        files: |
          ${{ github.workspace }}\bin\Release\AntiDupl.NET.WinForms.exe
      
    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v3
      env:
          VT_API_KEY: ${{ secrets.VT_API_KEY }}
      if: matrix.configuration == 'Publish' && env.VT_API_KEY != null
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        files: |
          ${{ github.workspace }}\out\Publish\AntiDupl.NET\AntiDupl.NET.WinForms.exe
      
    - if: matrix.configuration == 'Release'
      name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: "AntiDupl.NET-${{ steps.version.outputs.content }} build"
        path: |
              ${{ github.workspace }}\out\bin\AntiDupl.NET-${{ steps.version.outputs.content }}.exe
              ${{ github.workspace }}\out\bin\AntiDupl.NET-${{ steps.version.outputs.content }}.exe.hash.txt
              ${{ github.workspace }}\out\bin\AntiDupl.NET-${{ steps.version.outputs.content }}.7z
              ${{ github.workspace }}\out\bin\AntiDupl.NET-${{ steps.version.outputs.content }}.7z.hash.txt
      
    - if: matrix.configuration == 'Publish'
      name: Upload build SingleFilePortable
      uses: actions/upload-artifact@v3
      with:
        name: "AntiDupl.NET-${{ steps.version.outputs.content }} build SingleFilePortable"
        path: |
              ${{ github.workspace }}\out\Publish\AntiDupl.NET-${{ steps.version.outputs.content }}_SingleFilePortable.exe
              ${{ github.workspace }}\out\Publish\AntiDupl.NET-${{ steps.version.outputs.content }}_SingleFilePortable.exe.hash.txt
              ${{ github.workspace }}\out\Publish\AntiDupl.NET-${{ steps.version.outputs.content }}_SingleFilePortable.7z
              ${{ github.workspace }}\out\Publish\AntiDupl.NET-${{ steps.version.outputs.content }}_SingleFilePortable.7z.hash.txt
          
    - if: startswith( github.ref, 'refs/tags/') && matrix.configuration == 'Publish'
      name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}\out\Publish\AntiDupl.NET-${{ steps.version.outputs.content }}_SingleFilePortable.exe
        asset_name: "AntiDupl.NET-${{ github.ref_name }}_SingleFilePortable.exe"
        tag: ${{ github.ref }}
        overwrite: true
        release_name: "AntiDupl.NET ${{ github.ref_name }}"
          
    - if: startswith( github.ref, 'refs/tags/') && matrix.configuration == 'Release'
      name: Upload portable binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}\out\bin\AntiDupl.NET-${{ steps.version.outputs.content }}.exe
        asset_name: "AntiDupl.NET-${{ github.ref_name }}.exe"
        tag: ${{ github.ref }}
        overwrite: true
        release_name: "AntiDupl.NET ${{ github.ref_name }}"
